name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} using ${{ matrix.compiler }}
    strategy:
      matrix:
        compiler:
          - g++
          - clang++
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B .build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=Release -DLIBXID_ENABLE_TESTING=ON
      - name: Build
        run: |
          cmake --build .build --config Release
      - name: Test
        working-directory: ${{ github.workspace }}/.build
        run: |
          ctest -C Release
